apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels: #ensures that the Deployment is tied to Pods with the label app: auth.
        app: auth
    spec:
      containers:
        - name: auth #this is for logging purpose
          image: vladaminina/auth
          env:
            - name: JWT_KEY #inside container
              valueFrom:
                secretKeyRef: #from secret
                  name: jwt-secret #spesify whan run command kubectl create secret generic jwt-secret --from-literal=JWT_KEY=vlada
                  key: JWT_KEY #provided in command
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: auth # Corrected to be a map
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
