apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels: #ensures that the Deployment is tied to Pods with the label app: auth.
        app: expiration
    spec:
      containers:
        - name: expiration #this is for logging purpose
          image: vladaminina/expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "NATS_URL"
              value: "http://nats-srv:4222"
            - name: "NATS_CLUSTER_ID"
              value: "ticketing"
            - name: REDIS_HOST
              value: expiration-redis-srv
