name: deploy-manifests

on:
  push:
    branches:
      - main
    paths: 
      - 'ticket-project/infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing-platform # ticketing-platform that you set in digital ocean
      - run: kubectl apply -f ticket-project/infra/k8s
